---
extends: default

ignore:
  - terraform1/stacks/definitions/*/.terraform/*

rules:
  comments:
    ignore: |
      *.cc.yml
  brackets:
    ignore: |
      docker-compose.yml
  document-start:
    ignore: |
      ansible/
      docker-compose.yml
      .gitlab-ci.yml
      .pre-commit-config.yaml
      *.cc.yml
  line-length:
    ignore: |
      ansible/
      .gitlab-ci.yml
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
