version: '3.8'

networks:
  pspider-net:
    driver: bridge

services:
  pspider-db:
    image: postgres:15.3
    user: ${PSPIDER_REPO_PG_USERNAME}
    ports:
      - "${PSPIDER_REPO_PG_HOST_PORT}:${PSPIDER_REPO_PG_CONTAINER_PORT}"
    networks:
      - pspider-net
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready' ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${PSPIDER_REPO_PG_USERNAME}
      - POSTGRES_PASSWORD=${PSPIDER_REPO_PG_PASSWORD}
      - POSTGRES_DB=${PSPIDER_REPO_PG_DBNAME}
    volumes: [
      "./pspider_init.sql:/docker-entrypoint-initdb.d/pspider_init.sql",
      "pgdata:/var/lib/postgresql/data",
      "pgconf:/etc/postgresql",
      "pglog:/var/log/postgresql"
    ]

volumes:
  pgconf:
    driver: local
  pgdata:
    driver: local
  pglog:
    driver: local
